"""Shared specs and top-level config for the systems demo feature."""

from .systems_demo_feature import (
    _SYSTEMS_LIFECYCLE_SPEC,
    _SYSTEMS_RUNTIME_SPEC,
    _SYSTEMS_WINDOW_SPEC,
)

SYSTEMS_WINDOW_SPEC = _SYSTEMS_WINDOW_SPEC
SYSTEMS_RUNTIME_SPEC = _SYSTEMS_RUNTIME_SPEC
SYSTEMS_LIFECYCLE_SPEC = _SYSTEMS_LIFECYCLE_SPEC

__all__ = ["SYSTEMS_LIFECYCLE_SPEC", "SYSTEMS_RUNTIME_SPEC", "SYSTEMS_WINDOW_SPEC"]
