"""Shared specs and status constants for the Mandelbrot demo feature."""

from .mandelbrot_render import (
    MANDEL_KIND_CLEARED,
    MANDEL_KIND_COMPLETE,
    MANDEL_KIND_FAILED,
    MANDEL_KIND_IDLE,
    MANDEL_KIND_RUNNING_FOUR_SPLIT,
    MANDEL_KIND_RUNNING_ITERATIVE,
    MANDEL_KIND_RUNNING_ONE_SPLIT,
    MANDEL_KIND_RUNNING_RECURSIVE,
    MANDEL_KIND_STATUS,
    MANDEL_STATUS_SCOPE,
    MANDEL_STATUS_TOPIC,
)

__all__ = [
    "MANDEL_KIND_CLEARED",
    "MANDEL_KIND_COMPLETE",
    "MANDEL_KIND_FAILED",
    "MANDEL_KIND_IDLE",
    "MANDEL_KIND_RUNNING_FOUR_SPLIT",
    "MANDEL_KIND_RUNNING_ITERATIVE",
    "MANDEL_KIND_RUNNING_ONE_SPLIT",
    "MANDEL_KIND_RUNNING_RECURSIVE",
    "MANDEL_KIND_STATUS",
    "MANDEL_STATUS_SCOPE",
    "MANDEL_STATUS_TOPIC",
]
