"""Shared specs and top-level layout constants for the controls showcase feature."""

import pygame
from gui_do.features.data_driven_runtime import (
    RoutedRuntimeSpec,
    SceneCommandPaletteSpec,
    TaskPanelFocusToggleSpec,
)

_CONTROLS_RUNTIME_SPEC = RoutedRuntimeSpec(
    scene_name="control_showcase",
    task_panel_focus_toggles=(
        TaskPanelFocusToggleSpec(
            action_name="toggle_task_panel_focus_control_showcase",
            scene_name="control_showcase",
            key=pygame.K_F1,
        ),
    ),
    command_palette=SceneCommandPaletteSpec(
        key=pygame.K_F5,
        scene_name="control_showcase",
    ),
)


SHOWCASE_ROOT_MARGIN_X = 24
SHOWCASE_ROOT_MARGIN_TOP = 24
SHOWCASE_ROOT_MARGIN_BOTTOM = 86
SHOWCASE_CONTENT_PADDING_X = 4
SHOWCASE_CONTENT_PADDING_Y = 12
SHOWCASE_LABEL_HEIGHT = 18
SHOWCASE_LABEL_GAP = 4
SHOWCASE_CATEGORY_TAB_STRIP_HEIGHT = 34
SHOWCASE_CATEGORY_TAB_STRIP_GAP = 8
SHOWCASE_ROW_GAP = 8
SHOWCASE_BASICS_COL_GAP = 10
SHOWCASE_BASICS_INNER_GAP = 6

SHOWCASE_SLIDER_MINIMUM = 0.0
SHOWCASE_SLIDER_MAXIMUM = 100.0
SHOWCASE_SLIDER_DEFAULT_VALUE = 25.0
SHOWCASE_SCROLLBAR_CONTENT_SIZE = 1000
SHOWCASE_SCROLLBAR_VIEWPORT_SIZE = 240
SHOWCASE_SCROLLBAR_DEFAULT_OFFSET = 0
SHOWCASE_SCROLLBAR_STEP = 24

SHOWCASE_IMAGE_PATH = "data/images/realize.png"

SHOWCASE_TASK_PANEL_HEIGHT = 50
SHOWCASE_TASK_PANEL_HIDDEN_PEEK_PIXELS = 6
SHOWCASE_TASK_PANEL_ANIMATION_STEP_PX = 8
SHOWCASE_TASK_PANEL_BUTTON_WIDTH = 110
SHOWCASE_TASK_PANEL_BUTTON_HEIGHT = 30
SHOWCASE_TASK_PANEL_BUTTON_LEFT = 16
SHOWCASE_TASK_PANEL_BUTTON_TOP_OFFSET = 10
SHOWCASE_TASK_PANEL_SLOT_SPACING = 10

SHOWCASE_CATEGORY_TABS = (
    ("input", "Input"),
    ("display", "Display"),
    ("chrome", "Chrome"),
    ("composite", "Composite"),
    ("data_bound", "Data-Bound"),
)

SHOWCASE_BASICS_COLUMNS = 4
SHOWCASE_DATA_COLUMNS = 3
SHOWCASE_ADVANCED_COLUMNS = 2
SHOWCASE_EXTENDED_COLUMNS = 1

SHOWCASE_CATEGORY_ROW_GROUPS = {
    "display": frozenset((10, 11, 14, 15, 16, 17, 18)),
    "chrome": frozenset((140, 141, 142, 143)),
}

SHOWCASE_CATEGORY_ROW_RANGES = {
    "input": ((1, 9), (12, 12)),
    "data_bound": ((60, 99),),
    "composite": ((100, 139),),
}

SHOWCASE_MENU_BAR_HEIGHT = 28
SHOWCASE_MENU_TOOLS_EXCLUDE_LABELS = ("Open Command Palette (F5)",)


__all__ = [
    "_CONTROLS_RUNTIME_SPEC",
    "SHOWCASE_ADVANCED_COLUMNS",
    "SHOWCASE_BASICS_COL_GAP",
    "SHOWCASE_BASICS_COLUMNS",
    "SHOWCASE_BASICS_INNER_GAP",
    "SHOWCASE_CATEGORY_ROW_GROUPS",
    "SHOWCASE_CATEGORY_ROW_RANGES",
    "SHOWCASE_CATEGORY_TAB_STRIP_GAP",
    "SHOWCASE_CATEGORY_TAB_STRIP_HEIGHT",
    "SHOWCASE_CATEGORY_TABS",
    "SHOWCASE_CONTENT_PADDING_X",
    "SHOWCASE_CONTENT_PADDING_Y",
    "SHOWCASE_DATA_COLUMNS",
    "SHOWCASE_EXTENDED_COLUMNS",
    "SHOWCASE_IMAGE_PATH",
    "SHOWCASE_LABEL_GAP",
    "SHOWCASE_LABEL_HEIGHT",
    "SHOWCASE_MENU_BAR_HEIGHT",
    "SHOWCASE_MENU_TOOLS_EXCLUDE_LABELS",
    "SHOWCASE_ROOT_MARGIN_BOTTOM",
    "SHOWCASE_ROOT_MARGIN_TOP",
    "SHOWCASE_ROOT_MARGIN_X",
    "SHOWCASE_ROW_GAP",
    "SHOWCASE_SCROLLBAR_CONTENT_SIZE",
    "SHOWCASE_SCROLLBAR_DEFAULT_OFFSET",
    "SHOWCASE_SCROLLBAR_STEP",
    "SHOWCASE_SCROLLBAR_VIEWPORT_SIZE",
    "SHOWCASE_SLIDER_DEFAULT_VALUE",
    "SHOWCASE_SLIDER_MAXIMUM",
    "SHOWCASE_SLIDER_MINIMUM",
    "SHOWCASE_TASK_PANEL_ANIMATION_STEP_PX",
    "SHOWCASE_TASK_PANEL_BUTTON_HEIGHT",
    "SHOWCASE_TASK_PANEL_BUTTON_LEFT",
    "SHOWCASE_TASK_PANEL_BUTTON_TOP_OFFSET",
    "SHOWCASE_TASK_PANEL_BUTTON_WIDTH",
    "SHOWCASE_TASK_PANEL_HEIGHT",
    "SHOWCASE_TASK_PANEL_HIDDEN_PEEK_PIXELS",
    "SHOWCASE_TASK_PANEL_SLOT_SPACING",
]
