"""Compatibility re-export shim: all abstractions now live in gui_do.features.data_driven_runtime."""

from __future__ import annotations

try:
    from demo_features._import_bootstrap import ensure_repo_root_on_path
except ModuleNotFoundError:
    from _import_bootstrap import ensure_repo_root_on_path

ensure_repo_root_on_path()

from gui_do.features.data_driven_runtime import (
    build_tools_menu_entries,
    add_standard_scene_menu_strip,
    apply_accessibility_sequence,
    apply_accessibility_sequence_from_attrs,
    register_companion_logic_features,
    ensure_scene_scheduler,
    sorted_window_bindings,
    collect_window_toggle_controls,
    apply_window_toggle_accessibility,
    add_window_toggle_task_panel_controls,
    register_window_toggle_tooltips,
    initialize_locale_registry,
    bind_input_map_actions,
    register_descriptors,
    resolve_canvas_local_point,
    apply_runtime_scene_pristine_assets,
    bind_runtime_scene_exit_keys,
    prewarm_runtime_scenes,
    add_task_panel_button,
    add_task_panel_buttons,
    register_tooltip_specs,
    add_window_control,
    add_window_label,
    add_window_button,
    add_window_button_row,
    make_window_toggle_spec,
    make_scene_nav_action,
    make_exit_action,
    make_palette_open_action,
    make_static_accessibility_spec,
    instantiate_features_from_specs,
    register_features_from_specs,
    register_window_presentation_specs,
    register_window_tab_builders,
    build_tab_builder_specs,
    create_tab_control_from_specs,
    compute_tabbed_window_layout,
    register_window_tab_builder_specs,
    setup_feature_presenter_tabs,
    register_tab_update_handlers,
    create_presented_anchored_window,
    create_presented_window_from_spec,
    create_feature_presented_window,
    bind_feature_logic_aliases,
    setup_routed_feature_runtime,
    FeatureSpec,
    WindowSpec,
    RuntimeSceneSpec,
    ActionSpec,
    StaticAccessibilitySpec,
    CursorSpec,
    SceneRootSpec,
    AnchoredWindowSpec,
    LogicBindingSpec,
    TaskPanelButtonSpec,
    AccessibilitySequenceSpec,
    TabBuilderSpec,
    ActiveTabUpdateRouter,
    TabLayoutContext,
    TelemetryConfig,
    HostApplicationConfig,
    bootstrap_host_application,
)
